### ISSUE TITLE
Bug with the latest version pdf pdfrender

### ISSUE THREAD

**Issue by fpantigny** [ho-tex/pdfrender#3]
With the latest version of `pdfrender` (v. 1.7 2023-12-04), I have a bug with the following code:

```
\documentclass{article}
\usepackage{pdfrender}

\begin{document}

\newsavebox\test
\begin{lrbox}{\test}
Essai.
\end{lrbox}

\end{document}
```

I think the following initialization is missing the `pdfrender.dtx`:

`\def\PdfRender@PatchColorSetGroup{}`

**Comment by u-fischer** [comment]
No, it is simply a typo/copy&paste error. I should have used `\PdfRender@ColorSetGroupHook`. 

I will upload a new version. Try as work around

~~~~
 \makeatletter
\def\PdfRender@PatchColorSetGroup{\PdfRender@ColorSetGroupHook}
~~~~

**Comment by u-fischer** [comment]
I sent the fix to ctan.

**Comment by fpantigny** [comment]
Thanks.
